baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Pymtech S.A.S'
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
enableInlineShortcodes = true

[darkmode_js]
  paths = ["assets/js/darkmode.js"]

 

[params]
  author = 'Pymtech S.A.S'
  authorimage = '\images\pages\logo_pymptech_P_white_cloudsbg_squared.png'
  moto = 'Custom solutions to technify and modernize companies, powered by Pymtech.'
  description = ''
  disable_theme_toggle = false
  disable_stay_uptodate = false
  
  [params.p1]
    heading = "Our mission"
    image = "images/image_tree_homepage_our_mission.png"
    [[params.p1.content]]
      text = "Our mission at Pymtech is to help SMEs organize and optimize their internal processes by providing management software and personalized services that improve communication and operational efficiency, enabling them to grow sustainably."
  [params.p2]
    heading = "Our purpose"
    image = "images/image_purpose_homepage.png"
    [[params.p2.content]]
      text = "At Pymtech, we exist to empower small and medium-sized enterprises by organizing and optimizing their internal processes. Our goal is to solve internal communication problems through innovative software that efficiently channels information. We offer flexible subscriptions and custom development, providing technological solutions that evolve alongside our clients' needs. Additionally, we drive the growth of SMEs through the analysis of data acquired with our applications."
  [params.p3]
    heading = "Our values"
    [[params.p3.content]]
      text = "Transparency"
    [[params.p3.content]]
      text = "Autonomy"
    [[params.p3.content]]
      text = "Quality"
    [[params.p3.content]]
      text = "Commitment"
    [[params.p3.content]]
      text = "Adaptability"
    [[params.p3.links]]
      text = "Meet our investors and advisors"
      url = "#"
    [[params.p3.logos]]
      identifier = "a"
      image = "images/global/sample-logo.svg"
      alt = "a"
    [[params.p3.logos]]
      identifier = "b"
    [[params.p3.logos]]
      identifier = "c"
    [[params.p3.logos]]
      identifier = "d"
    [[params.p3.logos]]
      identifier = "e"
    [[params.p3.logos]]
      identifier = "f"
  [params.p4]
    heading = "From the blog"
    [[params.p4.content]]
      text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed."
  [params.p5]
    heading = "Stay Up to Date"
    [[params.p5.content]]
      text = "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque."
    action = "#"
    label = "Email address"
    placeholder = "Enter your email"
    button = "Notify me"

  [params.contact]
    email = 'pymtech@pymtech-co.com'
    phone = '+57 321-852-2691'
  [params.social_media]
    [params.social_media.github]
      enabled = true
      url = "https://github.com/pymtech-co"
    [params.social_media.facebook]
      enabled = true
      url = "https://facebook.com/nusserstudios"
    [params.social_media.instagram]
      enabled = true
      url = "https://instagram.com/pymtech.co"

  [menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.footer]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
    [markup.goldmark.typographer]
      apostrophe = '&rsquo;'
      disable = false
      ellipsis = '&hellip;'
      emDash = '&mdash;'
      enDash = '&ndash;'
      leftAngleQuote = '&laquo;'
      leftDoubleQuote = '&ldquo;'
      leftSingleQuote = '&lsquo;'
      rightAngleQuote = '&raquo;'
      rightDoubleQuote = '&rdquo;'
      rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
        title = true
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[taxonomies]
  category = "Categories"
  tag = "Tags"